#!/usr/bin/env node
// scripts/sync-agents.mjs — one set of rules, many front doors.
//
// AGENTS.md is canonical. Most agents (Codex, Cursor, Copilot's coding agent,
// Jules, Amp, Zed, Devin …) read it directly; the rest each look for their own
// filename and would otherwise open this repo with ZERO rules loaded. So we
// generate a small pointer file for each of those.
//
// The pointer is deliberately not a bare "see AGENTS.md": an agent that does not
// follow file references would then be bound by nothing. Each stub therefore
// restates the non-negotiable rules inline and points at AGENTS.md for the rest.
// Short enough to cost nothing, complete enough to be safe on its own.
//
// Symlinks were the obvious alternative and are the wrong tool: git checkouts on
// Windows default to `core.symlinks=false`, which turns each one into a text file
// containing a path. A generated file works everywhere.
//
//   node scripts/sync-agents.mjs           write/refresh every pointer file
//   node scripts/sync-agents.mjs --check   report drift, write nothing (exit 1 if stale)

import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { pathToFileURL } from "node:url";
import { at, parseFlags, readIfExists, writeIfChanged } from "./lib/util.mjs";

const CANONICAL = "AGENTS.md";

/** Each front door, with whatever frontmatter that tool needs to auto-load it. */
export const TARGETS = [
  { path: ".github/copilot-instructions.md", tool: "GitHub Copilot" },
  { path: "GEMINI.md", tool: "Gemini CLI" },
  {
    path: ".cursor/rules/00-agents.mdc",
    tool: "Cursor",
    frontmatter: ["---", "description: Project rules (canonical source: AGENTS.md)", "alwaysApply: true", "---"],
  },
  {
    path: ".windsurf/rules/agents.md",
    tool: "Windsurf",
    frontmatter: ["---", "trigger: always_on", "---"],
  },
  { path: ".clinerules/00-agents.md", tool: "Cline / Roo Code" },
  { path: ".junie/guidelines.md", tool: "JetBrains Junie" },
  { path: "CONVENTIONS.md", tool: "Aider" },
];

/** The rules that must survive even if the agent never opens AGENTS.md. */
const NON_NEGOTIABLE = [
  "**Read `AGENTS.md` first.** It holds the full working rules for this repo. Everything below is the short version.",
  "**Read before writing.** Open the file you are about to change; never edit from memory.",
  "**One command for quality gates, whatever the language: `npm run gate`** (`npm run gate:list` shows what it runs, `npm run gate test` runs one stage). Actual commands live in `package.json` → `vibe.gates`. Do not invent your own build/test command — if a gate is wrong, fix it there.",
  "**Verify before claiming.** \"Done\", \"fixed\" and \"passing\" require real `npm run gate` output. Never report success from inspection alone.",
  "**Finish 100%.** One task complete — code, tests, gates green — before starting the next.",
  "**No duplication.** Anything used from 2+ places gets extracted into a shared util. No dead code, no orphan files.",
  "**Never commit or push unless the owner asks**, and never rewrite pushed history.",
  "**One author per commit.** Do not add a `Co-Authored-By` line — not for yourself, not for anyone — nor a \"Generated with …\" line or a session link, whichever tool you are. A `commit-msg` hook removes every such trailer and CI fails the build if one lands anyway. Credit collaborators in the commit body instead.",
  "**Ask ONE question when genuinely unsure** instead of guessing.",
];

const ROUTES = [
  ["`docs/STACK.md`", "detected framework, where heavy logic belongs, gate commands (generated)"],
  ["`docs/ARCHITECTURE.md`", "layers, patterns, key decisions"],
  ["`docs/PRD.md`", "product scope and sensitive-feature guardrails"],
  ["`docs/FEATURES.md`", "per-screen / per-feature behavior"],
  ["`docs/TASKS.md`", "the phase checklist"],
  ["`docs/VERSIONING.md`", "release and version-bump rules"],
  ["`docs/archive/`", "full build history — read before deep work on a domain that has one"],
];

export function renderStub(target) {
  const lines = [...(target.frontmatter ?? [])];
  if (lines.length) lines.push("");
  lines.push(
    `# Project rules — ${target.tool}`,
    "",
    `<!-- GENERATED by \`npm run agents:sync\` from ${CANONICAL}. Do not hand-edit: your changes`,
    `     will be overwritten. Edit ${CANONICAL} and re-run the command. -->`,
    "",
    `> **Canonical rules: [\`${CANONICAL}\`](${CANONICAL}).** Read it before doing anything else in this repo.`,
    "",
    "## Non-negotiables",
    "",
  );
  for (const rule of NON_NEGOTIABLE) lines.push(`- ${rule}`);
  lines.push(
    "",
    "## Read docs by route, not wholesale",
    "",
    "| When you need | Read |",
    "|---|---|",
  );
  for (const [file, what] of ROUTES) lines.push(`| ${what} | ${file} |`);
  lines.push(
    "",
    "Cross-session issues live in **beads** (`bd ready`, `bd show <id>`, `bd update <id> --claim`,",
    "`bd close <id>`); `docs/TASKS.md` is the roadmap checklist, not an issue queue. If `bd` is not",
    `installed, skip it — it is optional. Full detail, as always, in \`${CANONICAL}\`.`,
    "",
  );
  return lines.join("\n");
}

export function sync({ check = false } = {}) {
  const stale = [];
  const written = [];
  for (const target of TARGETS) {
    const path = at(target.path);
    const next = renderStub(target);
    if (check) {
      if (readIfExists(path) !== next) stale.push(target.path);
      continue;
    }
    mkdirSync(dirname(path), { recursive: true });
    if (writeIfChanged(path, next)) written.push(target.path);
  }
  return { stale, written };
}

function main(argv) {
  // `--chek` used to fall through to the WRITE branch and exit 0, quietly
  // repairing the drift `--check` exists to report.
  const { flags, problems } = parseFlags(argv, { known: ["--check"] });
  if (problems.length) {
    process.stderr.write(`[agents] ${problems.join("; ")}\n`);
    process.stderr.write("usage: sync-agents.mjs [--check]\n");
    return 2;
  }
  if (!readIfExists(at(CANONICAL))) {
    process.stderr.write(`[agents] ${CANONICAL} is missing — nothing to point at. Aborting.\n`);
    return 1;
  }
  if (flags.has("--check")) {
    const { stale } = sync({ check: true });
    if (stale.length) {
      process.stderr.write(`[agents] out of date: ${stale.join(", ")}\n`);
      process.stderr.write("[agents] run `npm run agents:sync`\n");
      return 1;
    }
    process.stderr.write(`[agents] all ${TARGETS.length} pointer files are current\n`);
    return 0;
  }
  const { written } = sync();
  process.stderr.write(
    written.length
      ? `[agents] wrote ${written.length}: ${written.join(", ")}\n`
      : `[agents] all ${TARGETS.length} pointer files already current\n`,
  );
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.exit(main(process.argv.slice(2)));
}
